AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'bin/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'spec/**/*'
    - 'test/**/*'
    - 'vendor/bundle/**/*'
    - 'Gemfile'

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 150

Style/AsciiComments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Max: 16

Documentation:
    Enabled: false

NumericLiterals:
  MinDigits: 11

Style/BlockComments:
  Enabled: false

Rails/TimeZone:
  Enabled: false

Layout/TrailingBlankLines:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Rails/InverseOf:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Layout/TrailingWhitespace:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false