json.id                 user_extra.id
json.real_name          user_extra.real_name.to_s
json.cert_no            user_extra.cert_no.to_s
json.cert_type          user_extra.cert_type.to_s
json.memo               user_extra.memo.to_s
json.image              user_extra.image_path.to_s
json.status             user_extra.status.to_s
json.default            user_extra.default
json.created_at         user_extra.created_at.to_i