json.id         address.id
json.consignee  address.consignee.to_s
json.mobile     address.mobile.to_s
json.province   address.province
json.city       address.city
json.area       address.area
json.address    address.address.to_s
json.zip        address.zip.to_s
json.default    address.default
json.created_at address.created_at.to_i